//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Fadong.ZClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int Id { get; set; }
        public string mnuName { get; set; }
        public int mnuType { get; set; }
        public int loadType { get; set; }
        public int hasChild { get; set; }
        public string TgAssembly { get; set; }
        public string TgName { get; set; }
        public string Parent { get; set; }
        public int RefId { get; set; }
        public string mnuText { get; set; }
        public string mnuTextEng { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedUser { get; set; }
    }
}
