//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Com.Fadong.ZClient
{
    #region 컨텍스트
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    public partial class ZClientEntities : ObjectContext
    {
        #region 생성자
    
        /// <summary>
        /// 응용 프로그램 구성 파일의 'ZClientEntities' 섹션에서 검색된 연결 문자열을 사용하여 새 ZClientEntities 개체를 초기화합니다.
        /// </summary>
        public ZClientEntities() : base("name=ZClientEntities", "ZClientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 ZClientEntities 개체를 초기화합니다.
        /// </summary>
        public ZClientEntities(string connectionString) : base(connectionString, "ZClientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 ZClientEntities 개체를 초기화합니다.
        /// </summary>
        public ZClientEntities(EntityConnection connection) : base(connection, "ZClientEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 부분 메서드(Partial Method)
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<MenuMaster> MenuMasters
        {
            get
            {
                if ((_MenuMasters == null))
                {
                    _MenuMasters = base.CreateObjectSet<MenuMaster>("MenuMasters");
                }
                return _MenuMasters;
            }
        }
        private ObjectSet<MenuMaster> _MenuMasters;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<Enum> Enums
        {
            get
            {
                if ((_Enums == null))
                {
                    _Enums = base.CreateObjectSet<Enum>("Enums");
                }
                return _Enums;
            }
        }
        private ObjectSet<Enum> _Enums;

        #endregion

        #region AddTo 메서드
    
        /// <summary>
        /// MenuMasters EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToMenuMasters(MenuMaster menuMaster)
        {
            base.AddObject("MenuMasters", menuMaster);
        }
    
        /// <summary>
        /// Enums EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToEnums(Enum @enum)
        {
            base.AddObject("Enums", @enum);
        }

        #endregion

    }

    #endregion

    #region 엔터티
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZClientModel", Name="Enum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Enum : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 Enum 개체를 만듭니다.
        /// </summary>
        /// <param name="id">Id 속성의 초기 값입니다.</param>
        public static Enum CreateEnum(global::System.Int32 id)
        {
            Enum @enum = new Enum();
            @enum.Id = id;
            return @enum;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Entry
        {
            get
            {
                return _Entry;
            }
            set
            {
                OnEntryChanging(value);
                ReportPropertyChanging("Entry");
                _Entry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Entry");
                OnEntryChanged();
            }
        }
        private global::System.String _Entry;
        partial void OnEntryChanging(global::System.String value);
        partial void OnEntryChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Int32> _Value;
        partial void OnValueChanging(Nullable<global::System.Int32> value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedTime
        {
            get
            {
                return _CreatedTime;
            }
            set
            {
                OnCreatedTimeChanging(value);
                ReportPropertyChanging("CreatedTime");
                _CreatedTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedTime");
                OnCreatedTimeChanged();
            }
        }
        private global::System.String _CreatedTime;
        partial void OnCreatedTimeChanging(global::System.String value);
        partial void OnCreatedTimeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedTime
        {
            get
            {
                return _UpdatedTime;
            }
            set
            {
                OnUpdatedTimeChanging(value);
                ReportPropertyChanging("UpdatedTime");
                _UpdatedTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedTime");
                OnUpdatedTimeChanged();
            }
        }
        private global::System.String _UpdatedTime;
        partial void OnUpdatedTimeChanging(global::System.String value);
        partial void OnUpdatedTimeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Enum1
        {
            get
            {
                return _Enum1;
            }
            set
            {
                OnEnum1Changing(value);
                ReportPropertyChanging("Enum1");
                _Enum1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Enum1");
                OnEnum1Changed();
            }
        }
        private global::System.String _Enum1;
        partial void OnEnum1Changing(global::System.String value);
        partial void OnEnum1Changed();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZClientModel", Name="MenuMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuMaster : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 MenuMaster 개체를 만듭니다.
        /// </summary>
        /// <param name="id">Id 속성의 초기 값입니다.</param>
        /// <param name="mnuName">mnuName 속성의 초기 값입니다.</param>
        /// <param name="mnuType">mnuType 속성의 초기 값입니다.</param>
        /// <param name="loadType">loadType 속성의 초기 값입니다.</param>
        /// <param name="hasChild">hasChild 속성의 초기 값입니다.</param>
        /// <param name="refId">RefId 속성의 초기 값입니다.</param>
        /// <param name="mnuText">mnuText 속성의 초기 값입니다.</param>
        public static MenuMaster CreateMenuMaster(global::System.Int32 id, global::System.String mnuName, global::System.Int32 mnuType, global::System.Int32 loadType, global::System.Int32 hasChild, global::System.Int32 refId, global::System.String mnuText)
        {
            MenuMaster menuMaster = new MenuMaster();
            menuMaster.Id = id;
            menuMaster.mnuName = mnuName;
            menuMaster.mnuType = mnuType;
            menuMaster.loadType = loadType;
            menuMaster.hasChild = hasChild;
            menuMaster.RefId = refId;
            menuMaster.mnuText = mnuText;
            return menuMaster;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mnuName
        {
            get
            {
                return _mnuName;
            }
            set
            {
                OnmnuNameChanging(value);
                ReportPropertyChanging("mnuName");
                _mnuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mnuName");
                OnmnuNameChanged();
            }
        }
        private global::System.String _mnuName;
        partial void OnmnuNameChanging(global::System.String value);
        partial void OnmnuNameChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mnuType
        {
            get
            {
                return _mnuType;
            }
            set
            {
                OnmnuTypeChanging(value);
                ReportPropertyChanging("mnuType");
                _mnuType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mnuType");
                OnmnuTypeChanged();
            }
        }
        private global::System.Int32 _mnuType;
        partial void OnmnuTypeChanging(global::System.Int32 value);
        partial void OnmnuTypeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loadType
        {
            get
            {
                return _loadType;
            }
            set
            {
                OnloadTypeChanging(value);
                ReportPropertyChanging("loadType");
                _loadType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("loadType");
                OnloadTypeChanged();
            }
        }
        private global::System.Int32 _loadType;
        partial void OnloadTypeChanging(global::System.Int32 value);
        partial void OnloadTypeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hasChild
        {
            get
            {
                return _hasChild;
            }
            set
            {
                OnhasChildChanging(value);
                ReportPropertyChanging("hasChild");
                _hasChild = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasChild");
                OnhasChildChanged();
            }
        }
        private global::System.Int32 _hasChild;
        partial void OnhasChildChanging(global::System.Int32 value);
        partial void OnhasChildChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TgAssembly
        {
            get
            {
                return _TgAssembly;
            }
            set
            {
                OnTgAssemblyChanging(value);
                ReportPropertyChanging("TgAssembly");
                _TgAssembly = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TgAssembly");
                OnTgAssemblyChanged();
            }
        }
        private global::System.String _TgAssembly;
        partial void OnTgAssemblyChanging(global::System.String value);
        partial void OnTgAssemblyChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TgName
        {
            get
            {
                return _TgName;
            }
            set
            {
                OnTgNameChanging(value);
                ReportPropertyChanging("TgName");
                _TgName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TgName");
                OnTgNameChanged();
            }
        }
        private global::System.String _TgName;
        partial void OnTgNameChanging(global::System.String value);
        partial void OnTgNameChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parent
        {
            get
            {
                return _Parent;
            }
            set
            {
                OnParentChanging(value);
                ReportPropertyChanging("Parent");
                _Parent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parent");
                OnParentChanged();
            }
        }
        private global::System.String _Parent;
        partial void OnParentChanging(global::System.String value);
        partial void OnParentChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RefId
        {
            get
            {
                return _RefId;
            }
            set
            {
                OnRefIdChanging(value);
                ReportPropertyChanging("RefId");
                _RefId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefId");
                OnRefIdChanged();
            }
        }
        private global::System.Int32 _RefId;
        partial void OnRefIdChanging(global::System.Int32 value);
        partial void OnRefIdChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mnuText
        {
            get
            {
                return _mnuText;
            }
            set
            {
                OnmnuTextChanging(value);
                ReportPropertyChanging("mnuText");
                _mnuText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mnuText");
                OnmnuTextChanged();
            }
        }
        private global::System.String _mnuText;
        partial void OnmnuTextChanging(global::System.String value);
        partial void OnmnuTextChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mnuTextEng
        {
            get
            {
                return _mnuTextEng;
            }
            set
            {
                OnmnuTextEngChanging(value);
                ReportPropertyChanging("mnuTextEng");
                _mnuTextEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mnuTextEng");
                OnmnuTextEngChanged();
            }
        }
        private global::System.String _mnuTextEng;
        partial void OnmnuTextEngChanging(global::System.String value);
        partial void OnmnuTextEngChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedTime
        {
            get
            {
                return _CreatedTime;
            }
            set
            {
                OnCreatedTimeChanging(value);
                ReportPropertyChanging("CreatedTime");
                _CreatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedTime");
                OnCreatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedTime;
        partial void OnCreatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedTimeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedUser
        {
            get
            {
                return _CreatedUser;
            }
            set
            {
                OnCreatedUserChanging(value);
                ReportPropertyChanging("CreatedUser");
                _CreatedUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreatedUser");
                OnCreatedUserChanged();
            }
        }
        private global::System.String _CreatedUser;
        partial void OnCreatedUserChanging(global::System.String value);
        partial void OnCreatedUserChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedTime
        {
            get
            {
                return _UpdatedTime;
            }
            set
            {
                OnUpdatedTimeChanging(value);
                ReportPropertyChanging("UpdatedTime");
                _UpdatedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedTime");
                OnUpdatedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedTime;
        partial void OnUpdatedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedTimeChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedUser
        {
            get
            {
                return _UpdatedUser;
            }
            set
            {
                OnUpdatedUserChanging(value);
                ReportPropertyChanging("UpdatedUser");
                _UpdatedUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedUser");
                OnUpdatedUserChanged();
            }
        }
        private global::System.String _UpdatedUser;
        partial void OnUpdatedUserChanging(global::System.String value);
        partial void OnUpdatedUserChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortCutKey
        {
            get
            {
                return _ShortCutKey;
            }
            set
            {
                OnShortCutKeyChanging(value);
                ReportPropertyChanging("ShortCutKey");
                _ShortCutKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortCutKey");
                OnShortCutKeyChanged();
            }
        }
        private global::System.String _ShortCutKey;
        partial void OnShortCutKeyChanging(global::System.String value);
        partial void OnShortCutKeyChanged();

        #endregion

    }

    #endregion

}
