//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MCached
{
    #region 컨텍스트
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    public partial class dctx : ObjectContext
    {
        #region 생성자
    
        /// <summary>
        /// 응용 프로그램 구성 파일의 'dctx' 섹션에서 검색된 연결 문자열을 사용하여 새 dctx 개체를 초기화합니다.
        /// </summary>
        public dctx() : base("name=dctx", "dctx")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 dctx 개체를 초기화합니다.
        /// </summary>
        public dctx(string connectionString) : base(connectionString, "dctx")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 dctx 개체를 초기화합니다.
        /// </summary>
        public dctx(EntityConnection connection) : base(connection, "dctx")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 부분 메서드(Partial Method)
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_ADDINFO> D_ADDINFO
        {
            get
            {
                if ((_D_ADDINFO == null))
                {
                    _D_ADDINFO = base.CreateObjectSet<D_ADDINFO>("D_ADDINFO");
                }
                return _D_ADDINFO;
            }
        }
        private ObjectSet<D_ADDINFO> _D_ADDINFO;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_ADDINFOSPEC> D_ADDINFOSPEC
        {
            get
            {
                if ((_D_ADDINFOSPEC == null))
                {
                    _D_ADDINFOSPEC = base.CreateObjectSet<D_ADDINFOSPEC>("D_ADDINFOSPEC");
                }
                return _D_ADDINFOSPEC;
            }
        }
        private ObjectSet<D_ADDINFOSPEC> _D_ADDINFOSPEC;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_CASHFLOW> D_CASHFLOW
        {
            get
            {
                if ((_D_CASHFLOW == null))
                {
                    _D_CASHFLOW = base.CreateObjectSet<D_CASHFLOW>("D_CASHFLOW");
                }
                return _D_CASHFLOW;
            }
        }
        private ObjectSet<D_CASHFLOW> _D_CASHFLOW;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_HISTPRICES> D_HISTPRICES
        {
            get
            {
                if ((_D_HISTPRICES == null))
                {
                    _D_HISTPRICES = base.CreateObjectSet<D_HISTPRICES>("D_HISTPRICES");
                }
                return _D_HISTPRICES;
            }
        }
        private ObjectSet<D_HISTPRICES> _D_HISTPRICES;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_INSTRUMENT> D_INSTRUMENT
        {
            get
            {
                if ((_D_INSTRUMENT == null))
                {
                    _D_INSTRUMENT = base.CreateObjectSet<D_INSTRUMENT>("D_INSTRUMENT");
                }
                return _D_INSTRUMENT;
            }
        }
        private ObjectSet<D_INSTRUMENT> _D_INSTRUMENT;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_LEG> D_LEG
        {
            get
            {
                if ((_D_LEG == null))
                {
                    _D_LEG = base.CreateObjectSet<D_LEG>("D_LEG");
                }
                return _D_LEG;
            }
        }
        private ObjectSet<D_LEG> _D_LEG;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_RESET> D_RESET
        {
            get
            {
                if ((_D_RESET == null))
                {
                    _D_RESET = base.CreateObjectSet<D_RESET>("D_RESET");
                }
                return _D_RESET;
            }
        }
        private ObjectSet<D_RESET> _D_RESET;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<D_TRADE> D_TRADE
        {
            get
            {
                if ((_D_TRADE == null))
                {
                    _D_TRADE = base.CreateObjectSet<D_TRADE>("D_TRADE");
                }
                return _D_TRADE;
            }
        }
        private ObjectSet<D_TRADE> _D_TRADE;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<S_LOG> S_LOG
        {
            get
            {
                if ((_S_LOG == null))
                {
                    _S_LOG = base.CreateObjectSet<S_LOG>("S_LOG");
                }
                return _S_LOG;
            }
        }
        private ObjectSet<S_LOG> _S_LOG;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<C_LINK> C_LINK
        {
            get
            {
                if ((_C_LINK == null))
                {
                    _C_LINK = base.CreateObjectSet<C_LINK>("C_LINK");
                }
                return _C_LINK;
            }
        }
        private ObjectSet<C_LINK> _C_LINK;
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<C_PORTFOLIO> C_PORTFOLIO
        {
            get
            {
                if ((_C_PORTFOLIO == null))
                {
                    _C_PORTFOLIO = base.CreateObjectSet<C_PORTFOLIO>("C_PORTFOLIO");
                }
                return _C_PORTFOLIO;
            }
        }
        private ObjectSet<C_PORTFOLIO> _C_PORTFOLIO;

        #endregion

        #region AddTo 메서드
    
        /// <summary>
        /// D_ADDINFO EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_ADDINFO(D_ADDINFO d_ADDINFO)
        {
            base.AddObject("D_ADDINFO", d_ADDINFO);
        }
    
        /// <summary>
        /// D_ADDINFOSPEC EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_ADDINFOSPEC(D_ADDINFOSPEC d_ADDINFOSPEC)
        {
            base.AddObject("D_ADDINFOSPEC", d_ADDINFOSPEC);
        }
    
        /// <summary>
        /// D_CASHFLOW EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_CASHFLOW(D_CASHFLOW d_CASHFLOW)
        {
            base.AddObject("D_CASHFLOW", d_CASHFLOW);
        }
    
        /// <summary>
        /// D_HISTPRICES EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_HISTPRICES(D_HISTPRICES d_HISTPRICES)
        {
            base.AddObject("D_HISTPRICES", d_HISTPRICES);
        }
    
        /// <summary>
        /// D_INSTRUMENT EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_INSTRUMENT(D_INSTRUMENT d_INSTRUMENT)
        {
            base.AddObject("D_INSTRUMENT", d_INSTRUMENT);
        }
    
        /// <summary>
        /// D_LEG EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_LEG(D_LEG d_LEG)
        {
            base.AddObject("D_LEG", d_LEG);
        }
    
        /// <summary>
        /// D_RESET EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_RESET(D_RESET d_RESET)
        {
            base.AddObject("D_RESET", d_RESET);
        }
    
        /// <summary>
        /// D_TRADE EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToD_TRADE(D_TRADE d_TRADE)
        {
            base.AddObject("D_TRADE", d_TRADE);
        }
    
        /// <summary>
        /// S_LOG EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToS_LOG(S_LOG s_LOG)
        {
            base.AddObject("S_LOG", s_LOG);
        }
    
        /// <summary>
        /// C_LINK EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToC_LINK(C_LINK c_LINK)
        {
            base.AddObject("C_LINK", c_LINK);
        }
    
        /// <summary>
        /// C_PORTFOLIO EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToC_PORTFOLIO(C_PORTFOLIO c_PORTFOLIO)
        {
            base.AddObject("C_PORTFOLIO", c_PORTFOLIO);
        }

        #endregion

    }

    #endregion

    #region 엔터티
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="C_LINK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C_LINK : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 C_LINK 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static C_LINK CreateC_LINK(global::System.Decimal id)
        {
            C_LINK c_LINK = new C_LINK();
            c_LINK.ID = id;
            return c_LINK;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> LINKTYPE
        {
            get
            {
                return _LINKTYPE;
            }
            set
            {
                OnLINKTYPEChanging(value);
                ReportPropertyChanging("LINKTYPE");
                _LINKTYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LINKTYPE");
                OnLINKTYPEChanged();
            }
        }
        private Nullable<global::System.Int16> _LINKTYPE;
        partial void OnLINKTYPEChanging(Nullable<global::System.Int16> value);
        partial void OnLINKTYPEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                OnPARENT_IDChanging(value);
                ReportPropertyChanging("PARENT_ID");
                _PARENT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARENT_ID");
                OnPARENT_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _PARENT_ID;
        partial void OnPARENT_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CHILD_ID
        {
            get
            {
                return _CHILD_ID;
            }
            set
            {
                OnCHILD_IDChanging(value);
                ReportPropertyChanging("CHILD_ID");
                _CHILD_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHILD_ID");
                OnCHILD_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CHILD_ID;
        partial void OnCHILD_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnCHILD_IDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="C_PORTFOLIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C_PORTFOLIO : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 C_PORTFOLIO 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static C_PORTFOLIO CreateC_PORTFOLIO(global::System.Decimal id)
        {
            C_PORTFOLIO c_PORTFOLIO = new C_PORTFOLIO();
            c_PORTFOLIO.ID = id;
            return c_PORTFOLIO;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ISCOMPOUND
        {
            get
            {
                return _ISCOMPOUND;
            }
            set
            {
                OnISCOMPOUNDChanging(value);
                ReportPropertyChanging("ISCOMPOUND");
                _ISCOMPOUND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISCOMPOUND");
                OnISCOMPOUNDChanged();
            }
        }
        private Nullable<global::System.Int16> _ISCOMPOUND;
        partial void OnISCOMPOUNDChanging(Nullable<global::System.Int16> value);
        partial void OnISCOMPOUNDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BASECURRENCY
        {
            get
            {
                return _BASECURRENCY;
            }
            set
            {
                OnBASECURRENCYChanging(value);
                ReportPropertyChanging("BASECURRENCY");
                _BASECURRENCY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BASECURRENCY");
                OnBASECURRENCYChanged();
            }
        }
        private Nullable<global::System.Decimal> _BASECURRENCY;
        partial void OnBASECURRENCYChanging(Nullable<global::System.Decimal> value);
        partial void OnBASECURRENCYChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> PRF_TYPE
        {
            get
            {
                return _PRF_TYPE;
            }
            set
            {
                OnPRF_TYPEChanging(value);
                ReportPropertyChanging("PRF_TYPE");
                _PRF_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRF_TYPE");
                OnPRF_TYPEChanged();
            }
        }
        private Nullable<global::System.Int16> _PRF_TYPE;
        partial void OnPRF_TYPEChanging(Nullable<global::System.Int16> value);
        partial void OnPRF_TYPEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> OWNER_TYPE
        {
            get
            {
                return _OWNER_TYPE;
            }
            set
            {
                OnOWNER_TYPEChanging(value);
                ReportPropertyChanging("OWNER_TYPE");
                _OWNER_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OWNER_TYPE");
                OnOWNER_TYPEChanged();
            }
        }
        private Nullable<global::System.Int16> _OWNER_TYPE;
        partial void OnOWNER_TYPEChanging(Nullable<global::System.Int16> value);
        partial void OnOWNER_TYPEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OWNER_ID
        {
            get
            {
                return _OWNER_ID;
            }
            set
            {
                OnOWNER_IDChanging(value);
                ReportPropertyChanging("OWNER_ID");
                _OWNER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OWNER_ID");
                OnOWNER_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _OWNER_ID;
        partial void OnOWNER_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnOWNER_IDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_ADDINFO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_ADDINFO : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_ADDINFO 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_ADDINFO CreateD_ADDINFO(global::System.Decimal id)
        {
            D_ADDINFO d_ADDINFO = new D_ADDINFO();
            d_ADDINFO.ID = id;
            return d_ADDINFO;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_ADDINFOSPEC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_ADDINFOSPEC : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_ADDINFOSPEC 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_ADDINFOSPEC CreateD_ADDINFOSPEC(global::System.Decimal id)
        {
            D_ADDINFOSPEC d_ADDINFOSPEC = new D_ADDINFOSPEC();
            d_ADDINFOSPEC.ID = id;
            return d_ADDINFOSPEC;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_CASHFLOW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_CASHFLOW : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_CASHFLOW 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_CASHFLOW CreateD_CASHFLOW(global::System.Decimal id)
        {
            D_CASHFLOW d_CASHFLOW = new D_CASHFLOW();
            d_CASHFLOW.ID = id;
            return d_CASHFLOW;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_HISTPRICES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_HISTPRICES : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_HISTPRICES 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_HISTPRICES CreateD_HISTPRICES(global::System.Decimal id)
        {
            D_HISTPRICES d_HISTPRICES = new D_HISTPRICES();
            d_HISTPRICES.ID = id;
            return d_HISTPRICES;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OPRICE
        {
            get
            {
                return _OPRICE;
            }
            set
            {
                OnOPRICEChanging(value);
                ReportPropertyChanging("OPRICE");
                _OPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OPRICE");
                OnOPRICEChanged();
            }
        }
        private Nullable<global::System.Decimal> _OPRICE;
        partial void OnOPRICEChanging(Nullable<global::System.Decimal> value);
        partial void OnOPRICEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HPRICE
        {
            get
            {
                return _HPRICE;
            }
            set
            {
                OnHPRICEChanging(value);
                ReportPropertyChanging("HPRICE");
                _HPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HPRICE");
                OnHPRICEChanged();
            }
        }
        private Nullable<global::System.Decimal> _HPRICE;
        partial void OnHPRICEChanging(Nullable<global::System.Decimal> value);
        partial void OnHPRICEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LPRICE
        {
            get
            {
                return _LPRICE;
            }
            set
            {
                OnLPRICEChanging(value);
                ReportPropertyChanging("LPRICE");
                _LPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LPRICE");
                OnLPRICEChanged();
            }
        }
        private Nullable<global::System.Decimal> _LPRICE;
        partial void OnLPRICEChanging(Nullable<global::System.Decimal> value);
        partial void OnLPRICEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CPRICE
        {
            get
            {
                return _CPRICE;
            }
            set
            {
                OnCPRICEChanging(value);
                ReportPropertyChanging("CPRICE");
                _CPRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CPRICE");
                OnCPRICEChanged();
            }
        }
        private Nullable<global::System.Decimal> _CPRICE;
        partial void OnCPRICEChanging(Nullable<global::System.Decimal> value);
        partial void OnCPRICEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SETTLE
        {
            get
            {
                return _SETTLE;
            }
            set
            {
                OnSETTLEChanging(value);
                ReportPropertyChanging("SETTLE");
                _SETTLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SETTLE");
                OnSETTLEChanged();
            }
        }
        private Nullable<global::System.Decimal> _SETTLE;
        partial void OnSETTLEChanging(Nullable<global::System.Decimal> value);
        partial void OnSETTLEChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_INSTRUMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_INSTRUMENT : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_INSTRUMENT 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_INSTRUMENT CreateD_INSTRUMENT(global::System.Decimal id)
        {
            D_INSTRUMENT d_INSTRUMENT = new D_INSTRUMENT();
            d_INSTRUMENT.ID = id;
            return d_INSTRUMENT;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> INSTYPE
        {
            get
            {
                return _INSTYPE;
            }
            set
            {
                OnINSTYPEChanging(value);
                ReportPropertyChanging("INSTYPE");
                _INSTYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INSTYPE");
                OnINSTYPEChanged();
            }
        }
        private Nullable<global::System.Int16> _INSTYPE;
        partial void OnINSTYPEChanging(Nullable<global::System.Int16> value);
        partial void OnINSTYPEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISIN
        {
            get
            {
                return _ISIN;
            }
            set
            {
                OnISINChanging(value);
                ReportPropertyChanging("ISIN");
                _ISIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISIN");
                OnISINChanged();
            }
        }
        private global::System.String _ISIN;
        partial void OnISINChanging(global::System.String value);
        partial void OnISINChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EXTRN_ID1
        {
            get
            {
                return _EXTRN_ID1;
            }
            set
            {
                OnEXTRN_ID1Changing(value);
                ReportPropertyChanging("EXTRN_ID1");
                _EXTRN_ID1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EXTRN_ID1");
                OnEXTRN_ID1Changed();
            }
        }
        private global::System.String _EXTRN_ID1;
        partial void OnEXTRN_ID1Changing(global::System.String value);
        partial void OnEXTRN_ID1Changed();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EXTRN_ID2
        {
            get
            {
                return _EXTRN_ID2;
            }
            set
            {
                OnEXTRN_ID2Changing(value);
                ReportPropertyChanging("EXTRN_ID2");
                _EXTRN_ID2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EXTRN_ID2");
                OnEXTRN_ID2Changed();
            }
        }
        private global::System.String _EXTRN_ID2;
        partial void OnEXTRN_ID2Changing(global::System.String value);
        partial void OnEXTRN_ID2Changed();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ISSUEDAY
        {
            get
            {
                return _ISSUEDAY;
            }
            set
            {
                OnISSUEDAYChanging(value);
                ReportPropertyChanging("ISSUEDAY");
                _ISSUEDAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISSUEDAY");
                OnISSUEDAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _ISSUEDAY;
        partial void OnISSUEDAYChanging(Nullable<global::System.DateTime> value);
        partial void OnISSUEDAYChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> STARTDAY
        {
            get
            {
                return _STARTDAY;
            }
            set
            {
                OnSTARTDAYChanging(value);
                ReportPropertyChanging("STARTDAY");
                _STARTDAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STARTDAY");
                OnSTARTDAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _STARTDAY;
        partial void OnSTARTDAYChanging(Nullable<global::System.DateTime> value);
        partial void OnSTARTDAYChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ENDDAY
        {
            get
            {
                return _ENDDAY;
            }
            set
            {
                OnENDDAYChanging(value);
                ReportPropertyChanging("ENDDAY");
                _ENDDAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ENDDAY");
                OnENDDAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _ENDDAY;
        partial void OnENDDAYChanging(Nullable<global::System.DateTime> value);
        partial void OnENDDAYChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> EXP_PERIOD_COUNT
        {
            get
            {
                return _EXP_PERIOD_COUNT;
            }
            set
            {
                OnEXP_PERIOD_COUNTChanging(value);
                ReportPropertyChanging("EXP_PERIOD_COUNT");
                _EXP_PERIOD_COUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXP_PERIOD_COUNT");
                OnEXP_PERIOD_COUNTChanged();
            }
        }
        private Nullable<global::System.Int16> _EXP_PERIOD_COUNT;
        partial void OnEXP_PERIOD_COUNTChanging(Nullable<global::System.Int16> value);
        partial void OnEXP_PERIOD_COUNTChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> EXP_PERIOD_UNIT
        {
            get
            {
                return _EXP_PERIOD_UNIT;
            }
            set
            {
                OnEXP_PERIOD_UNITChanging(value);
                ReportPropertyChanging("EXP_PERIOD_UNIT");
                _EXP_PERIOD_UNIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXP_PERIOD_UNIT");
                OnEXP_PERIOD_UNITChanged();
            }
        }
        private Nullable<global::System.Int16> _EXP_PERIOD_UNIT;
        partial void OnEXP_PERIOD_UNITChanging(Nullable<global::System.Int16> value);
        partial void OnEXP_PERIOD_UNITChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CURRENCY
        {
            get
            {
                return _CURRENCY;
            }
            set
            {
                OnCURRENCYChanging(value);
                ReportPropertyChanging("CURRENCY");
                _CURRENCY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CURRENCY");
                OnCURRENCYChanged();
            }
        }
        private Nullable<global::System.Decimal> _CURRENCY;
        partial void OnCURRENCYChanging(Nullable<global::System.Decimal> value);
        partial void OnCURRENCYChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CALLABLE
        {
            get
            {
                return _CALLABLE;
            }
            set
            {
                OnCALLABLEChanging(value);
                ReportPropertyChanging("CALLABLE");
                _CALLABLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CALLABLE");
                OnCALLABLEChanged();
            }
        }
        private Nullable<global::System.Int16> _CALLABLE;
        partial void OnCALLABLEChanging(Nullable<global::System.Int16> value);
        partial void OnCALLABLEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> PUTABLE
        {
            get
            {
                return _PUTABLE;
            }
            set
            {
                OnPUTABLEChanging(value);
                ReportPropertyChanging("PUTABLE");
                _PUTABLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PUTABLE");
                OnPUTABLEChanged();
            }
        }
        private Nullable<global::System.Int16> _PUTABLE;
        partial void OnPUTABLEChanging(Nullable<global::System.Int16> value);
        partial void OnPUTABLEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ISDIGITAL
        {
            get
            {
                return _ISDIGITAL;
            }
            set
            {
                OnISDIGITALChanging(value);
                ReportPropertyChanging("ISDIGITAL");
                _ISDIGITAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISDIGITAL");
                OnISDIGITALChanged();
            }
        }
        private Nullable<global::System.Int16> _ISDIGITAL;
        partial void OnISDIGITALChanging(Nullable<global::System.Int16> value);
        partial void OnISDIGITALChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ISOTC
        {
            get
            {
                return _ISOTC;
            }
            set
            {
                OnISOTCChanging(value);
                ReportPropertyChanging("ISOTC");
                _ISOTC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISOTC");
                OnISOTCChanged();
            }
        }
        private Nullable<global::System.Int16> _ISOTC;
        partial void OnISOTCChanging(Nullable<global::System.Int16> value);
        partial void OnISOTCChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ISGENERIC
        {
            get
            {
                return _ISGENERIC;
            }
            set
            {
                OnISGENERICChanging(value);
                ReportPropertyChanging("ISGENERIC");
                _ISGENERIC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISGENERIC");
                OnISGENERICChanged();
            }
        }
        private Nullable<global::System.Int16> _ISGENERIC;
        partial void OnISGENERICChanging(Nullable<global::System.Int16> value);
        partial void OnISGENERICChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> VMODEL
        {
            get
            {
                return _VMODEL;
            }
            set
            {
                OnVMODELChanging(value);
                ReportPropertyChanging("VMODEL");
                _VMODEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VMODEL");
                OnVMODELChanged();
            }
        }
        private Nullable<global::System.Decimal> _VMODEL;
        partial void OnVMODELChanging(Nullable<global::System.Decimal> value);
        partial void OnVMODELChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CATAG_ID
        {
            get
            {
                return _CATAG_ID;
            }
            set
            {
                OnCATAG_IDChanging(value);
                ReportPropertyChanging("CATAG_ID");
                _CATAG_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CATAG_ID");
                OnCATAG_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CATAG_ID;
        partial void OnCATAG_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnCATAG_IDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CONTRSIZE
        {
            get
            {
                return _CONTRSIZE;
            }
            set
            {
                OnCONTRSIZEChanging(value);
                ReportPropertyChanging("CONTRSIZE");
                _CONTRSIZE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONTRSIZE");
                OnCONTRSIZEChanged();
            }
        }
        private Nullable<global::System.Decimal> _CONTRSIZE;
        partial void OnCONTRSIZEChanging(Nullable<global::System.Decimal> value);
        partial void OnCONTRSIZEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_LEG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_LEG : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_LEG 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_LEG CreateD_LEG(global::System.Decimal id)
        {
            D_LEG d_LEG = new D_LEG();
            d_LEG.ID = id;
            return d_LEG;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_RESET")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_RESET : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_RESET 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_RESET CreateD_RESET(global::System.Decimal id)
        {
            D_RESET d_RESET = new D_RESET();
            d_RESET.ID = id;
            return d_RESET;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="D_TRADE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class D_TRADE : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 D_TRADE 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static D_TRADE CreateD_TRADE(global::System.Decimal id)
        {
            D_TRADE d_TRADE = new D_TRADE();
            d_TRADE.ID = id;
            return d_TRADE;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="S_LOG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class S_LOG : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 S_LOG 개체를 만듭니다.
        /// </summary>
        /// <param name="id">ID 속성의 초기 값입니다.</param>
        public static S_LOG CreateS_LOG(global::System.Decimal id)
        {
            S_LOG s_LOG = new S_LOG();
            s_LOG.ID = id;
            return s_LOG;
        }

        #endregion

        #region 단순 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATED_TIME
        {
            get
            {
                return _CREATED_TIME;
            }
            set
            {
                OnCREATED_TIMEChanging(value);
                ReportPropertyChanging("CREATED_TIME");
                _CREATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_TIME");
                OnCREATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATED_TIME;
        partial void OnCREATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CREATED_USER
        {
            get
            {
                return _CREATED_USER;
            }
            set
            {
                OnCREATED_USERChanging(value);
                ReportPropertyChanging("CREATED_USER");
                _CREATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_USER");
                OnCREATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _CREATED_USER;
        partial void OnCREATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnCREATED_USERChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATED_TIME
        {
            get
            {
                return _UPDATED_TIME;
            }
            set
            {
                OnUPDATED_TIMEChanging(value);
                ReportPropertyChanging("UPDATED_TIME");
                _UPDATED_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_TIME");
                OnUPDATED_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATED_TIME;
        partial void OnUPDATED_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATED_TIMEChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UPDATED_USER
        {
            get
            {
                return _UPDATED_USER;
            }
            set
            {
                OnUPDATED_USERChanging(value);
                ReportPropertyChanging("UPDATED_USER");
                _UPDATED_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATED_USER");
                OnUPDATED_USERChanged();
            }
        }
        private Nullable<global::System.Decimal> _UPDATED_USER;
        partial void OnUPDATED_USERChanging(Nullable<global::System.Decimal> value);
        partial void OnUPDATED_USERChanged();

        #endregion

    }

    #endregion

}
